### ISSUE TITLE
What about CLI support

### ISSUE THREAD

**Issue by AndyOGo** [thejoshwolfe/yazl#29]
Offering shebanged binary version would be cool.
Globbing some files/folders and zipping them.

**Comment by andrewrk** [comment]
Sounds like a great idea for a different package.

**Comment by thejoshwolfe** [comment]
as @andrewrk said, yazl is designed as a library that can be used to build abstractions on top of. A command line program is a great example of a program that would use yazl as a library.

There are two main reasons I don't want a command line program in yazl's package: I don't want people depending on yazl as a library to get a command line program they don't want. And I don't want to intermix support for a command line program with support for a library.

Command line programs are very different to support, because their requirements are not well established. For example, you're suggesting globbing for files/folders, but what about an exclude pattern? What about heuristics for attempting to compress vs simply storing the file? What about modifying an existing zipfile in place? There's no end to the possible features for a user-facing program, but a library is pretty well defined. I know which features should be in yazl and which should not.

Making a command line program is still a cool idea. I don't want to say that no one should do it. But I'm not motivated to make a serious command line program, simply because I would never use it as opposed to InfoZip's `zip` command line program. You or anyone else is welcome and encouraged to make a command line program that uses yazl; that's what yazl is here for!

If you'd like some inspiration, I actually do have an example of a command line utility at `examples/zip.js` that I've been using to test yazl. But as the path suggests, I don't support that as a serious program; it's just an example.

**Comment by AndyOGo** [comment]
@andrewrk @thejoshwolfe 
Thanks for your quick feedback.
I agree to have it within `yazl` would bloat it. A separate cli tool is indeed the best way.

And thanks for this great library.
