### ISSUE TITLE
passing a string to addBuffer almost works

### ISSUE THREAD

**Issue by lfdoherty** [thejoshwolfe/yazl#35]
Specifically, all the content seems to come through, but the zipfile size metadata is wrong if the string contains Unicode characters (because it uses the string length.)

Not really a bug, since you shouldn't pass a string to that function, but it does make debugging harder if you do it by accident. I'd suggest a Buffer.isBuffer(...) check on that parameter.

**Comment by thejoshwolfe** [comment]
I've considered type safety parameter validation like you're suggesting, but I don't really think it's the right approach. I know it can certainly be helpful sometimes, but there's a slippery slope there. What about checking the string parameters aren't really buffers? What about checking that strings and numbers aren't getting confused?

The common case is that the programmer didn't make a mistake and the types are all as expected.
Optimal performance in that case is to do no checks. I don't think it's worth slowing everyone down to help some people debug. It would make the library a little bit friendlier to use, but my hope is that the documentation fills that role instead of runtime checks.
